apiVersion: v1
kind: Pod
metadata:
 name: nginx-pod
 labels:
  app: nginx
spec:
 containers:
  - name: nginx
    image : nginx
    ports:
     - containerPort : 80
    volumeMounts:
     - name : nginx-config
       mountPath: /usr/share/nginx/html
 volumes:
  - name: nginx-config
    configMap:
      name: nginx-config

